name: 更新规则集

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0:00（北京时间 8:00）运行
  workflow_dispatch:     # 允许手动触发

jobs:
  update-rules:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史记录以确保所有文件都被检出
        
      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml
          
      - name: 确保自定义规则目录存在
        run: |
          mkdir -p rulesets/custom
          
      - name: 更新规则
        env:
          BARK_URL: ${{ secrets.BARK_URL }}
        run: |
          python scripts/consolidate_rules.py update --notify
          
      - name: 提交更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add rulesets/classical/
          git add rule_stats.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "自动更新规则 $(date +'%Y-%m-%d')" && git push) 